#!/usr/bin/env php
<?php
// require __DIR__ . '/bootstrap/app.php';

define('PUBLIC_PATH', __DIR__ . '/public/');
define('BASE_PATH', __DIR__ . '/');
define('VERSION', '3.4.2');

use App\Services\Boot;
use App\Command\XCat;

// Vendor Autoload
require BASE_PATH . '/vendor/autoload.php';

Boot::loadEnv();
Boot::setDebug();
Boot::setVersion(VERSION);
// config time zone
Boot::setTimezone();
// Init db
Boot::bootDb();

/***
 * ss-panel xcat script
 */
// use App\Command\XCat;

$cat = new XCat($argv);
$cat->boot();
